[workspace]
members = [
    "tensorflow_pluggable_device_sys",
    "backend",
    "VultenRs",
]
resolver = "2"

[profile.release]
lto = "fat"
strip = "symbols"
codegen-units = 1

[profile.bench]
lto = "fat"
strip = "symbols"
codegen-units = 1